---
- name: Install Quagga package
  become: "True"
  package:
    name: quagga
    state: present

- name: Remove zebra=no in daemons file
  become: "True"
  lineinfile:
    path: /etc/quagga/daemons
    regexp: '^zebra=no\s+'
    state: absent

- name: Enable zebra daemon
  become: "True"
  lineinfile:
    path: /etc/quagga/daemons
    line: 'zebra=yes'
    insertbefore: '^bgpd=no|bgpd=yes'
    state: present
  notify: Restart quagga

- name: zebra.conf
  become: "True"
  template:
    src: zebra.conf.j2
    dest: /etc/quagga/zebra.conf
    owner: quagga
    group: quagga
    mode: 0640
  notify: Restart quagga

- name: OSPF
  include_tasks: ospf.yml
  when: quagga_ospf is defined

- name: BGP
  include_tasks: bgp.yml
  when: quagga_bgp is defined
