---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: r1
    box: ubuntu/trusty64
    interfaces:
      - auto_config: "True"
        network_name: private_network
        type: static
        ip: 192.168.29.11
    groups:
      - ospf
provisioner:
  name: ansible
  inventory:
    group_vars:
      ospf:
        quagga_ospfd_enabled: "True"
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    v: true
    sudo: true
  lint:
    name: flake8
